# Generated by Django 4.2.11 on 2024-05-18 08:12

from django.db import migrations, models
import django.db.models.deletion
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_shipment__estimated_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='_estimated_arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='_estimated_departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_fee',
            field=models.DecimalField(decimal_places=2, help_text='in dollars($)', max_digits=100),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(default=logistics.models.Invoice.get_invoice_id, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('receipient_email', models.EmailField(max_length=254)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='logistics.shipment')),
            ],
        ),
    ]
