# Generated by Django 4.2.11 on 2024-05-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_alter_shipment__estimated_arrival_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_id',
            new_name='invoice_number',
        ),
    ]
