# Generated by Django 4.2.11 on 2024-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_shipment_additional_charges_shipment_additional_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='additional_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='insurance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tax_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vat_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
