# Generated by Django 4.2.11 on 2024-05-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_alter_shipment_additional_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='package_description',
            field=models.TextField(default='consignment to rivera'),
            preserve_default=False,
        ),
    ]
