# Generated by Django 4.2.11 on 2024-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_shipment_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tax_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vat_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=models.CharField(choices=[('registered', 'registered'), ('received', 'received'), ('processing', 'processing'), ('in transit', 'in transit'), ('on hold', 'on hold')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transitlog',
            name='status',
            field=models.CharField(choices=[('arrived', 'arrived'), ('processing', 'processing'), ('dispatched', 'dispatched'), ('on hold', 'on hold')], max_length=10),
        ),
    ]
