

services:
  - type: web
    plan: starter
    name: titansexpress
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn cargo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

      - key: DATABASE_URL
      
        value: postgresql://arcticxpress:Wdbtdpe51sbQsroUeLrTFgvVOk3Qe5O1@dpg-cqcne9tumphs73fhfmeg-a/arcticxpress:5432/titansexpress
        





